window.QUOTES_DATA = [
  { text: "walking on water and developing software from a specification are easy if both are frozen.", attr: "edward v. berard" },
  { text: "if debugging is the process of removing software bugs, then programming must be the process of putting them in.", attr: "edsger dijkstra" },
  { text: "software and cathedrals are much the same — first we build them, then we pray.", attr: "sam redwine" },
  { text: "the first rule of optimization: don't.", attr: "michael a. jackson" },
  { text: "the most disastrous thing that you can ever learn is your first programming language.", attr: "alan kay" },
  { text: "computers are good at following instructions, but not at reading your mind.", attr: "donald knuth" },
  { text: "the function of good software is to make the complex appear simple.", attr: "grady booch" },
  { text: "talk is cheap. show me the code.", attr: "linus torvalds" },
  { text: "most good programmers do programming not because they expect to get paid or be adored by the public, but because it is fun.", attr: "linus torvalds" },
  { text: "first, solve the problem. then, write the code.", attr: "john johnson" },
  { text: "good code is its own best documentation.", attr: "steve mcconnell" },
  { text: "the best error message is the one that never shows up.", attr: "thomas fuchs" },
  { text: "a good programmer is someone who always looks both ways before crossing a one-way street.", attr: "doug linder" },
  { text: "programs must be written for people to read, and only incidentally for machines to execute.", attr: "harold abelson" },
  { text: "the purpose of software engineering is to control complexity, not to create it.", attr: "pamela zave" },
  { text: "code is like humor. when you have to explain it, it's bad.", attr: "cory house" },
  { text: "one of my most productive days was throwing away 1000 lines of code.", attr: "ken thompson" },
  { text: "before software can be reusable it first has to be usable.", attr: "ralph johnson" },
  { text: "software is a great combination between artistry and engineering.", attr: "bill gates" },
  { text: "debugging is twice as hard as writing the code in the first place.", attr: "brian kernighan" },
  { text: "the art of programming is the art of organizing complexity.", attr: "edsger dijkstra" },
  { text: "every great developer you know got there by solving problems they were unqualified to solve.", attr: "patrick mckenzie" },
  { text: "don't comment bad code — rewrite it.", attr: "brian kernighan" },
  { text: "there are only two hard things in computer science: cache invalidation and naming things.", attr: "phil karlton" },
  { text: "the cheapest, fastest, and most reliable components are those that aren't there.", attr: "gordon bell" },
  { text: "make it work, make it right, make it fast.", attr: "kent beck" },
  { text: "have you tried turning it off and on again?", attr: "it crowd" },
  { text: "the most important property of a program is whether it accomplishes the intention of its user.", attr: "c.a.r. hoare" },
  { text: "if you think you know what you're doing, you're probably wrong.", attr: "c.a.r. hoare" },
  { text: "object-oriented programming is an exceptionally bad idea which could only have originated in california.", attr: "edsger dijkstra" },
  { text: "perl: the only language that looks the same before and after rsa encryption.", attr: "keith bostic" },
  { text: "without requirements or design, programming is the art of adding bugs to an empty text file.", attr: "louis srygley" },

  { text: "sudo rm -rf / is not a joke. it's a career ender.", attr: "unknown" },
  { text: "there are 10 types of people: those who understand hex and everyone else.", attr: "unknown" },
  { text: "documentation? we don't need no stinking documentation.", attr: "developer folklore" },
  { text: "99 little bugs in the code. take one down, patch it around. 127 little bugs in the code.", attr: "unknown" },
  { text: "it's not a bug, it's an undocumented feature.", attr: "developer folklore" },
  { text: "the cloud is just someone else's computer.", attr: "unknown" },
  { text: "there's no place like 127.0.0.1.", attr: "unknown" },
  { text: "git blame is not a moral judgment. usually.", attr: "unknown" },
  { text: "every time you git push --force to main, a senior dev loses a year of their life.", attr: "unknown" },
  { text: "if at first you don't succeed, call it version 1.0.", attr: "unknown" },
  { text: "tabs vs spaces is the trolley problem of software development.", attr: "unknown" },
  { text: "legacy code is just code that makes money.", attr: "unknown" },
  { text: "docker: solving the 'works on my machine' problem by making everything nobody's machine.", attr: "unknown" },
  { text: "yaml is a language designed to make humans feel like parsers.", attr: "unknown" },
  { text: "regex is write-once read-never code.", attr: "unknown" },
  { text: "production is just a fancy word for 'where things go to die.'", attr: "unknown" },
  { text: "console.log is a perfectly valid debugging strategy.", attr: "unknown" },
  { text: "dark mode is not a preference. it is a necessity.", attr: "unknown" },
  { text: "vim has two modes: one that beeps and one that deletes everything.", attr: "unknown" },
  { text: "the best refactor is the one you don't have to explain to your manager.", attr: "unknown" },
  { text: "ship it. you can apologize in the patch notes.", attr: "unknown" },
  { text: "it works on my machine is not a valid bug report.", attr: "unknown" },
];