window.QUOTES_DATA = [
  { text: "security is not a product, but a process.", attr: "bruce schneier" },
  { text: "if you think technology can solve your security problems, then you don't understand the problems.", attr: "bruce schneier" },
  { text: "the only truly secure system is one that is powered off, cast in a block of concrete and sealed in a lead-lined room.", attr: "gene spafford" },
  { text: "there are two types of companies: those that have been hacked and those that don't know yet.", attr: "john chambers" },
  { text: "amateurs hack systems. professionals hack people.", attr: "bruce schneier" },
  { text: "security is always excessive until it's not enough.", attr: "robbie sinclair" },
  { text: "privacy is not something that i'm merely entitled to, it's an absolute prerequisite.", attr: "marlon brando" },
  { text: "the internet interprets censorship as damage and routes around it.", attr: "john gilmore" },
  { text: "encryption works. properly implemented strong crypto systems are one of the few things that you can rely on.", attr: "edward snowden" },
  { text: "the question is not whether you're paranoid. the question is whether you're paranoid enough.", attr: "william gibson" },
  { text: "a team of security researchers is no match for an army of miscreants.", attr: "james bamford" },
  { text: "given enough eyeballs, all bugs are shallow.", attr: "eric s. raymond" },
  { text: "security vulnerabilities are the natural result of complexity.", attr: "gary mcgraw" },
  { text: "every system has a shadow: the attack surface you haven't mapped yet.", attr: "dan geer" },
  { text: "the threat is always more creative than the defense.", attr: "dan geer" },
  { text: "risk management is the foundation of all security decisions.", attr: "bruce schneier" },
  { text: "complexity is the enemy of security.", attr: "bruce schneier" },
  { text: "attacks always get better, they never get worse.", attr: "niels ferguson" },
  { text: "never underestimate the determination of a kid who is time-rich and cash-poor.", attr: "cory doctorow" },
  { text: "the greatest threat to security is the illusion of security.", attr: "bruce schneier" },
  { text: "in security, there is no perimeter. there is only exposure.", attr: "john kindervag" },
  { text: "zero trust: never trust, always verify.", attr: "john kindervag" },
  { text: "social engineering bypasses all technology.", attr: "kevin mitnick" },
  { text: "the human element is the most vulnerable element of any security system.", attr: "kevin mitnick" },
  { text: "companies spend millions of dollars on firewalls and ignore the biggest security risk: people.", attr: "kevin mitnick" },
  { text: "i'm not a hacker because i'm bad. i'm a hacker because i'm curious.", attr: "kevin mitnick" },
  { text: "patch or perish.", attr: "richard clarke" },
  { text: "in cyberspace, the offense has the advantage.", attr: "william j. lynn iii" },
  { text: "a nation that loses control of its cyber infrastructure has lost sovereignty.", attr: "michael hayden" },
  { text: "defense in depth is the only sane architecture.", attr: "gary stoneburner" },
  { text: "cryptography is the essential building block of independence for organisations on the internet.", attr: "julian assange" },
  { text: "don't roll your own crypto. it's been said a thousand times because it's been violated a thousand times.", attr: "matt blaze" },
  { text: "the fundamental problem with public-key infrastructure is that it puts control in the wrong hands.", attr: "peter gutmann" },

  { text: "security through obscurity is not security. it's wishful thinking.", attr: "unknown" },
  { text: "never trust input. validate everything. assume nothing.", attr: "unknown" },
  { text: "the most dangerous word in security is 'probably.'", attr: "unknown" },
  { text: "patch early, patch often, patch before they get there.", attr: "unknown" },
  { text: "the insider threat is the one you already gave the keys to.", attr: "unknown" },
  { text: "log everything. you won't know what you need until you need it.", attr: "unknown" },
  { text: "sql injection is twenty-five years old and still in the top ten.", attr: "unknown" },
  { text: "your backup is not a backup until you've tested the restore.", attr: "unknown" },
  { text: "assume breach. design from inside out, not outside in.", attr: "unknown" },
  { text: "certificates expire. certificate monitoring often doesn't.", attr: "unknown" },
  { text: "oauth is authorization, not authentication. every few years someone has to relearn this.", attr: "unknown" },
  { text: "security audits find what you were looking for. red teams find what you weren't.", attr: "unknown" },
  { text: "least privilege is not optional. it's mandatory and most people skip it.", attr: "unknown" },
  { text: "a penetration test is not a security program. it's a snapshot in time.", attr: "unknown" },
  { text: "crypto is like a high-tech fortress — the walls are strong but the gates are the weak point.", attr: "unknown" },
  { text: "the cve database is a graveyard of 'should have been caught in code review.'", attr: "unknown" },
  { text: "every open port is a conversation. make sure you want that conversation.", attr: "unknown" },
  { text: "air gaps don't protect you from a usb drive in the parking lot.", attr: "unknown" },
  { text: "2fa won't stop everything. but it'll stop most things.", attr: "unknown" },
  { text: "the cloud didn't change your security posture. it changed who owns which part of it.", attr: "unknown" },
];