window.QUOTES_DATA = [
  { text: "simplicity is the soul of efficiency.", attr: "unknown" },
  { text: "there is no spoon. there is no silver bullet. there is only hard work.", attr: "unknown" },
  { text: "premature optimization is the root of all evil.", attr: "donald knuth" },
  { text: "the best code is no code. the second best is code that is clear and simple.", attr: "unknown" },
  { text: "build it right, then build it fast. not the other way around.", attr: "unknown" },
  { text: "the operating system is the most critical piece of software.", attr: "unknown" },
  { text: "a computer is a state machine. threads are for people who can't program state machines.", attr: "linus torvalds" },
  { text: "the kernel doesn't care about your feelings. only your syscalls.", attr: "unknown" },
  { text: "memory leaks are just memory with a sense of ownership.", attr: "unknown" },
  { text: "everything is a tradeoff. performance, correctness, maintainability — pick two.", attr: "unknown" },
  { text: "the scheduler is not fair. it is merely less unfair than alternatives.", attr: "unknown" },
  { text: "a race condition is just a bug that only appears when you're watching.", attr: "unknown" },
  { text: "deadlock is what happens when everyone waits for someone else to move first.", attr: "unknown" },
  { text: "the cache is always wrong. the cache is always necessary.", attr: "unknown" },
  { text: "if it compiles, it is correct. if it runs, you are lucky.", attr: "unknown" },
  { text: "the filesystem is the contract between your data and the machine.", attr: "unknown" },
  { text: "interrupts are the operating system's way of saying 'something actually matters right now.'", attr: "unknown" },
  { text: "virtual memory is the art of lying to processes about how much ram they have.", attr: "unknown" },
  { text: "context switching has a cost. invisible to applications. very visible to benchmarks.", attr: "unknown" },
  { text: "a process that doesn't die cleanly is a process that's still afraid.", attr: "unknown" },
  { text: "unix: everything is a file. windows: everything is a registry key. someone was wrong.", attr: "unknown" },
  { text: "the pipe is the most elegant ipc mechanism ever invented.", attr: "unix philosophy" },
  { text: "signals are how the kernel says 'no, really, stop now.'", attr: "unknown" },
  { text: "swap is where performance goes to die gracefully.", attr: "unknown" },
  { text: "copy-on-write is laziness elevated to an architectural principle.", attr: "unknown" },
  { text: "a buffer overflow is what happens when you forget that arrays end.", attr: "unknown" },
  { text: "the stack grows down. the heap grows up. they meet in the middle and argue.", attr: "unknown" },
  { text: "garbage collection is just paying memory debt in installments.", attr: "unknown" },
  { text: "systems crash for a reason. the reason is always in the logs, if you kept the logs.", attr: "unknown" },
  { text: "concurrency is hard because time is hard.", attr: "unknown" },
  { text: "make it work, make it right, make it fast. in that order.", attr: "kent beck" },
  { text: "an abstraction is useful until it isn't. then it's a trap.", attr: "unknown" },
  { text: "the difference between a good system and a great one is what happens when it fails.", attr: "unknown" },
  { text: "observability is not monitoring. monitoring tells you something is wrong. observability tells you why.", attr: "unknown" },
  { text: "uptime is not reliability. graceful degradation is reliability.", attr: "unknown" },
  { text: "you can't have strong consistency, high availability, and partition tolerance simultaneously. choose your regret.", attr: "cap theorem" },
  { text: "distributed systems are just single systems with more ways to lie about their state.", attr: "unknown" },
  { text: "a reboot solves more problems than any patch.", attr: "unknown" },
  { text: "the kernel panic is the operating system saying 'i give up. cleanly.'", attr: "unknown" },
  { text: "alignment matters. in bytes and in teams.", attr: "unknown" },
  { text: "the process table is a graveyard with live inhabitants.", attr: "unknown" },
  { text: "i/o is always the bottleneck. until it's the cpu. until it's the network.", attr: "unknown" },
  { text: "you can't benchmark a system you don't understand.", attr: "unknown" },
  { text: "a good system handles the unhappy path as gracefully as the happy path.", attr: "unknown" },
  { text: "the only bug-free code is code that does nothing.", attr: "unknown" },
  { text: "caching is trading space for time. everyone wants the deal. nobody likes the debt.", attr: "unknown" },
  { text: "design for failure. failure will not wait for an invitation.", attr: "unknown" },
  { text: "posix is a promise. linux is the promise kept, mostly.", attr: "unknown" },
  { text: "systemd divided the unix world. the unix world needed dividing.", attr: "unknown" },
  { text: "the oom killer is not cruel. it is calculating.", attr: "unknown" },
  { text: "threads share memory. sharing is caring until it isn't.", attr: "unknown" },
  { text: "the best ipc is the one you don't need.", attr: "unknown" },
  { text: "a well-tuned system hums. a poorly tuned one screams slowly.", attr: "unknown" },
  { text: "strace is the x-ray machine of systems debugging.", attr: "unknown" },
  { text: "every abstraction leaks under enough pressure.", attr: "joel spolsky" },
  { text: "the real bottleneck is always the part you didn't measure.", attr: "unknown" },
];